language: php
dist: precise
sudo: false
git:
    depth: 1

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.app/cache

env:
  global:
    - deps="no"
    - SYMFONY_VERSION=""
    - CHECK_PHP_SYNTAX="no"
    - SYMFONY_DEPRECATIONS_HELPER="weak"
    - ENABLE_CODE_COVERAGE="false"

matrix:
  fast_finish: true
  include:
    # Symfony 3.4
    - php: 7.1
      env:
        - SYMFONY_VERSION="3.4.*"
        - TWIG_VERSION="2.x-dev"
        - CHECK_PHP_SYNTAX="yes"
    # stable (most recent stable versions)
    - php: 7.2
      env:
        - SYMFONY_VERSION="3.4.*"
        - TWIG_VERSION="2.x-dev"
        - CHECK_PHP_SYNTAX="yes"

before_install:
  - stty cols 120
  - INI_FILE=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo memory_limit = -1 >> $INI_FILE
  - echo session.gc_probability = 0 >> $INI_FILE
  - echo opcache.enable_cli = 1 >> $INI_FILE
  - if [[ "SYMFONY_VERSION" == "2.8.*" || "SYMFONY_VERSION" == 3.* ]]; then export SYMFONY_DEPRECATIONS_HELPER="strict"; fi;
  - if [[ "$ENABLE_CODE_COVERAGE" != "true" && "$TRAVIS_EVENT_TYPE" != "cron" ]]; then rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini; fi;
  - composer self-update
  - if [[ "$SYMFONY_VERSION" != "" ]]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
  - if [[ "$TWIG_VERSION" != "" ]]; then composer require "twig/twig:${TWIG_VERSION}" --no-update; fi;

install:
  - composer update --prefer-dist --no-interaction --no-suggest --no-progress --ansi $COMPOSER_FLAGS
  - if [[ "$ENABLE_CODE_COVERAGE" == "true" && "$TRAVIS_EVENT_TYPE" == "cron" ]]; then composer require --dev satooshi/php-coveralls; fi

after_success: |
    if [[ "$ENABLE_CODE_COVERAGE" == "true" && "$TRAVIS_EVENT_TYPE" == "cron" ]]; then php vendor/bin/coveralls -v --config .coveralls.yml; fi;
