language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  - SYMFONY_VERSION=v2.8
  - SYMFONY_VERSION=v3.3
  - SYMFONY_VERSION=origin/master

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php -d memory_limit=-1 composer.phar install

script: phpunit

after_success:
  - coveralls
